export const ADD_USER = "ADD-USER";
export const FAILUER = "FAILUER";
export const GET_USER = "GET_USER";
export const CONVRSATION = "CONVRATION";
export const MESSAGE="MESSAGE";
export const SEARCH_USER = "SEARCH_USER";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const GET_MESSAGE = "GET_MESSAGE";
export const SEND_FILE = "SEND_FILE";
export const INCOMINGMEASSAGE = "INCOMINGMEASSAGE"